<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCommentsByArticle($min, $max, $id)
	{
			$qb = $this->getEntityManager()->createQueryBuilder('a')
    		->select('a', 'c')
    		->from('AppBundle:Article', 'a')
    		->innerJoin('AppBundle:Comment', 'c')
    		->where('a.id = :id')
            ->andWhere('c.article = :article')
            ->setParameter('id', $id)
            ->setParameter('article', $id)
            ->setMaxResults($max)
        	->setFirstResult($min);

    		return $qb->getQuery()->getResult();
	}
}
